 profile-name  = "terra"
 aws-region    = "us-east-1"
instance_type = "t2.micro"
key           = "terraansi"
key-path      = "/home/ec2-user/.ssh/terraansi.pub"
my-ip         = "0.0.0.0/0"
public_cidr   = "10.0.1.0/24"
vpc_cidr      = "10.0.0.0/16"
